import Head from 'next/head'
import {GiUsaFlag, GiBrazilFlag} from 'react-icons/gi'
import {AiFillLinkedin, AiFillInstagram, AiFillBehanceSquare, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import devll from '../../public/dev-ll.webp'
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import cards from "../data/cards.json"

export default function Home() {
  return (
    <>
      <Head>
        <title>SirLucasLima Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Open+Sans&family=Work+Sans:wght@700&display=swap" rel="stylesheet"></link>
      </Head>
      <main className='px-10 bg-zinc-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-red-400'>developedbysir</h1>
            <ul className='flex items-center'>
              <li><GiBrazilFlag className='cursor-pointer text-gray-200'/></li>
              <li><a className='bg-purple-600 text-gray-100 px-4 py-2 rounded-md ml-8' href="#">resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl text-teal-600 font-medium'>Sir Lucas Lima</h2>
            <h3 className='text-2xl py-2 text-gray-100'>Developer and designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-100'>Freelancer providing services for programming and design needs. Join me down below and let's get cracking!</p>
          </div>
          <div className='flex text-5xl justify-center gap-8 py-3 text-gray-500'>
            <AiFillLinkedin className='hover:animate-bounce  transform transition duration-300 ease-out hover:text-yellow-400'/>
            <AiFillGithub className='hover:animate-spin transform transition duration-300 ease-out hover:text-yellow-400'/>
            <AiFillBehanceSquare className='hover:animate-bounce transform transition duration-300 ease-out hover:text-yellow-400'/>
            <AiFillInstagram className='hover:animate-spin transform transition duration-300 ease-out hover:text-yellow-400'/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src="/dev-ll.webp" alt={'deved'} fill style={{objectFit:"cover"}}/>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className="text-teal-500"> agencies </span>consulted for <span className="text-teal-500">startups </span> and collaborated with talanted people to create digital products for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design, financial consultancy, but mainly programming.
            </p>
          </div>

          {cards.map(item => (
            <div>
              <Image src={item.img} key={item.img} alt={item.title} width={100} height={100}/>
            </div>
          ))}

        </section>
      </main>
    </>
  )
}
 